Feature/ms/redazione architettura
Spaghetti-Code-G6/swe-docs pull request #151
Opened 2021-06-30 18:01 UTC by gpaparaz

2021-07-12 07:53 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
> +\glossario{Sequelize} è un ORM (Object Relational Mapping) che mappa oggetti a database relazionali attraverso lo standard SQL. Grazie ad esso funziona con tutti i database.
Io eliminerei proprio quella frase

2021-07-12 07:56 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
ultimamente in distance matrix ho dovuto aggiunger anche [ml-hclust](https://www.npmjs.com/package/ml-hclust) , una libreria che permette di fare clustering gerarchico. vedete voi se è il caso di aggiungerlo. al link che ho mandato trovate tutte le informazioni per aggiungerlo

2021-07-12 08:01 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
da aggiungere anche [noUiSlider](https://refreshless.com/nouislider/): un framework (consigliato da materialize) per gestire gli slider nei vari grafici.

2021-07-12 08:02 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
e sarebbe da aggiungere anche [materializecss](https://materializecss.com/) che è il framework che (à la bootstrap) gestisce la parte di ui

2021-07-12 08:04 UTC, rizzostefano requested changes
aggiungere le tecnologie indicate nei commenti (ed eliminare la frase segnalata da martin)

2021-07-12 16:20 UTC, gpaparaz commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
è nell'altra PR che è stata approvata, infatti ho visto che ci sono già dei conflitti tra questo ramo e il principale

2021-07-12 16:22 UTC, gpaparaz commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
grazie 1

2021-07-12 16:22 UTC, gpaparaz commented on esterni/manuale_sviluppatore/src/2_tecnologie.tex
grazie 2

2021-07-15 12:56 UTC, rizzostefano submitted a review, later dismissed

2021-07-16 12:19 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/6_estendere.tex
> +un'ulteriore factory per la creazione del presenter e delle compmonenti della visualizzazione.
typo: componenti

2021-07-16 12:20 UTC, rizzostefano commented on esterni/manuale_sviluppatore/src/6_estendere.tex
> +Se necessario infatti il modello della visualizzazione alla quale si desidera aggiungere una
rimuovere "infatti" -> Se necessario, il modello....

2021-07-16 12:24 UTC, rizzostefano submitted a review, later dismissed

2021-07-17 10:16 UTC, paguz42 submitted a review, later dismissed

2021-07-17 13:14 UTC, merged