Fix/pd p/correzioni varie
Spaghetti-Code-G6/swe-docs pull request #152
Opened 2021-07-03 10:38 UTC by gpaparaz

2021-07-06 20:40 UTC, Archetipo95 submitted a review, later dismissed

2021-07-06 20:40 UTC, Archetipo95 commented on esterni/piano_di_progetto/src/4_pianificazione.tex
> +\subsubsection*{Attività}
cosa fa questo asterisco?

2021-07-09 08:10 UTC, Neskelogth submitted a review, later dismissed

2021-07-12 07:51 UTC, rizzostefano requested changes
vedo che ci sono degli scatti di versione un pò strani: del tipo che da 1.4.3 si va subito a 1.4.5. e 1.4.4?
attenzione che ho visto sparsi in giro diversi refusi. dateci un'occhiata con aspell e poi pushate

2021-07-15 12:52 UTC, rizzostefano approved these changes

2021-07-16 09:51 UTC, merged