Sistemate tabelle requisiti
Spaghetti-Code-G6/swe-docs pull request #25
Opened 2021-02-17 16:02 UTC by Neskelogth

2021-02-17 17:28 UTC, danielcontro requested changes
- Manca la riga relativa alle modifiche nel registro
- sarebbe da fixare la tabella fonti-requisiti: aggiungere \\\\ nell'ultimo elemento dei \makecell che non so perchè si è perso e spezzare diversamente i requisiti del capitolato

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/2_descrizione_generale.tex
> +Inoltre è stato deciso di supportare le ultime versioni delle alternative più diffuse, quindi Firefox dalla versione 85.0.0, Opera dalla versione 74.0.0, e Safari per Mac dalla versione 14.0.0.
"Il prodotto, secondo quanto specificato in \textsc{VE\_2020\_12\_17} e in \<documento verbale interno\>, dovrà supportare i seguenti browser a partire dalla versione specificata:
\<tabella con i browser e la versione a partire dalla quale sono supportati\>"

Direi di modificare così la frase, se preferite non fare la tabella (anche se Tullio ha più volte espresso la preferenza di quest'ultime) manterrei comunque la prima frase, specificando a seguire solo i browser e la versione a partire dalla quale il nostro prodotto li supporta. Sarebbe necessario fare un incontro ed un verbale per decidere i browser supportati di modo da avere il riferimento preciso (in VE non si parla di Opera e Safari)

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & L'applicativo deve essere supportato nel browser Google Chrome dalla versione 87.0.0
```suggestion
        & L'applicativo deve essere supportato dal browser Google Chrome dalla versione 87.0.0
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & L'applicativo deve essere supportato nel browser Mozilla Firefox dalla versione 85.0.0
```suggestion
        & L'applicativo deve essere supportato dal browser Mozilla Firefox dalla versione 85.0.0
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & L'applicativo deve essere supportato nel browser Opera dalla versione 74.0.0
```suggestion
        & L'applicativo deve essere supportato dal browser Opera dalla versione 74.0.0
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & L'applicativo deve essere supportato nel browser Safari, nella sua versione per Mac, dalla versione 14.0.0
```suggestion
        & L'applicativo deve essere supportato dal browser Safari, nella sua versione per Mac, dalla versione 14.0.0
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & VE\_2020\_12\_17 \\
```suggestion
        & \textsc{VE\_2020\_12\_17} \\
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & VE\_2020\_12\_17 \\
```suggestion
        & \textsc{VE\_2020\_12\_17} \\
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & Interno \\
Usare verbale interno

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/req_vincolo.tex
> +        & Interno \\
Usare verbale interno

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/fonte_requisiti.tex
> +    VE\_2020\_12\_17 &
```suggestion
        \textsc{VE\_2020\_12\_17} &
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/requisiti_fonte.tex
> +    RVO6 & VE\_2020\_12\_17 \\
```suggestion
    RVO5 & \textsc{VE\_2020\_12\_17} \\
    RVO6 & \textsc{VE\_2020\_12\_17} \\
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/requisiti_fonte.tex
>      RVo3 & Capitolato \\
```suggestion
    RVO3 & Capitolato \\
```

2021-02-17 17:28 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/requisiti/requisiti_fonte.tex
> +    RVO8 & Interno \\
Usare codice verbale interno

2021-02-24 14:35 UTC, Neskelogth commented
Ho sistemato quello che avevi detto, solo che non c'è un verbale interno a cui posso fare riferimento per quanto riguarda la versione dei browser da supportare, quindi l'ho lasciata senza riferimenti

2021-02-25 13:27 UTC, danielcontro reviewed
Nel grafico dell'UC4.7 si passa da 4.7.1 a 4.7.3, bisognerebbe scalare i numeri degli UC, eliminare il 4.7.2 ancora esplicitato più sotto.
L'UC5 è ancora presente, va eliminato e gli UC6-10 vanno scalati di numero, e portati a subsection.
Per entrambi i punti vanno conformate di conseguenza le tabelle: 
- requisiti;
- fonte-requisiti; 
- requisito-fonti;
- riepilogo.

2021-02-25 13:27 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/2_descrizione_generale.tex
> +	Broswer & Versione minima\\
```suggestion
	Browser & Versione\\
```

2021-02-25 13:27 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/2_descrizione_generale.tex
> +\end{tabular}
Centrare la tabella (separandola dalla riga precedente), scrivere in grassetto gli header e aggiungere la caption

2021-02-25 13:27 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/2_descrizione_generale.tex
>  \label{sub:supporto_browser}
Credo sia il caso di eliminare la subsection essendo sostanzialmente vuota e lasciare la parte del supporto dei browser dentro i vincoli progettuali (controllare che nel registro delle modifiche v1.0.1 non si rompa)

2021-02-25 13:54 UTC, Neskelogth commented
La parte degli use case l'ho lasciata apposta da parte, volevo sistemare una cosa alla volta, aprirò un'altra PR quando li avrò sistemati tutti

2021-02-27 11:24 UTC, danielcontro approved these changes
Ricordarsi di modificare le tabelle dei requisiti, UC4.7 e UC5-10

2021-02-27 11:24 UTC, merged