Corretti UC
Spaghetti-Code-G6/swe-docs pull request #27
Opened 2021-03-01 10:13 UTC by Neskelogth

2021-03-04 08:08 UTC, Archetipo95 requested changes
Ricontrolla la punteggiatura finale forse non le ho segnalate tutte. Per il resto mi sembra scritta bene e si capisce. Forse è meglio che gli dia un'occhiata anche qualche ex analista.

2021-03-04 08:08 UTC, Archetipo95 commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +    \item \textbf{Postcondizione}:  Viene caricato il dataset desiderato dall'utente o viene visualizzato un messaggio d'errore;
Manca punteggiatura finale

2021-03-04 08:08 UTC, Archetipo95 commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +				\item Viene visualizzato un messaggio di errore(UC5)
Manca punteggiatura finale

2021-03-04 08:08 UTC, Archetipo95 commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +				\item Viene visualizzato un messaggio di errore(UC6)
Manca punteggiatura finale

2021-03-04 08:08 UTC, Archetipo95 commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +				\item Viene visualizzato un messaggio di errore(UC7)
Manca punteggiatura finale

2021-03-04 10:22 UTC, danielcontro reviewed
- Bisogna aggiornare le tabelle dei requisiti secondo le modifiche fatte;
- Le precondizioni vanno ricontrollate (stati del sistema, non decisioni o cose fatte dall'utente);
- Le postcondizioni non devono esplicitare la gestione degli errori
- Eliminare i riferimenti all'utente se non presente come attore principale

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +    \item \textbf{Postcondizione}:  Viene caricato il dataset desiderato dall'utente con i metadati di tipo assegnati o viene visualizzato un messaggio d'errore;
```suggestion
    \item \textbf{Postcondizione}:  Viene caricato il dataset selezionato dall'utente con i metadati di tipo assegnati;
```

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +			\item La web-app comunica al server la decisione dell'utente;
```suggestion
```

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +            \item Il server fa il fetch dei dati;
```suggestion
            \item Il sistema effettua il fetch dei dati dalla fonte selezionata;
```

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +\end{itemize}
- Correggere postcondizione
- Rimuovere il riferimento all'utente in precondizione
- rimuovere il riferimento al passaggio delle info da webapp
- specificare meglio l'estensione sia nello scenario che nell'UC che estende

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +\end{figure}
- Il diagramma credo sia nella posizione sbagliata;
- UCS1.3 non può avere come sottouc UCS1.4;
- Puoi mettere tutto dentro il diagramma di UCS1

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/ucs1.tex
> +        \end{enumerate}
- Rimuovere il riferimento all'utente in precondizione, vengono selezionate query e non file di configurazione;
- Correggere post (rimuovere visualizzazione errore);
- Specificare meglio lo scenario principale

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
> +    \item \textbf{Descrizione}: L'utente seleziona un file csv del suo dispositivo;
L'utente deve selezionare l'import di dati da csv e poi il file; rimuovere il riferimento al dispositivo

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
> +			\item L'utente seleziona il file csv di dati da importare.
Specificare meglio

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
> +
Vengono selezionate query, non file di configurazione (dettaglio implementativo)

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
> +    \item \textbf{Postcondizione}:  Viene selezionato l'input da database e il file di configurazione;
Correggere

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
>      \item \textbf{Precondizione}:   L'utente decide di caricare i dati mediante un database;
La precondizione non è una decisione ma uno stato del sistema

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
> +    \item \textbf{Precondizione}:   L'utente decide di caricare i file da un file csv;
La precondizione non è una decisione ma uno stato del sistema

2021-03-04 10:22 UTC, danielcontro commented on esterni/analisi_dei_requisiti/src/uc/uc1.tex
>          \end{enumerate}
Specificare meglio

2021-03-09 18:26 UTC, Archetipo95 submitted a review, later dismissed

2021-03-09 19:46 UTC, Archetipo95 approved these changes

2021-03-09 19:59 UTC, merged