PdQ/correzioni segnalate
Spaghetti-Code-G6/swe-docs pull request #30
Opened 2021-03-05 09:40 UTC by gpaparaz

Ho aggiunto un'altra metrica nel capitolo 2 circa il budget;
ho preparato l'appendice A  per inserire i risultati dei test fatti per la RP, aggiunto un paragrafo che parla dei risultati in RR
ho ampliato l'appendice C inserendo le nostre considerazioni su cose avvenute in RR

2021-03-05 16:37 UTC, danielcontro requested changes
Aggiungerei una descrizione sulle metriche che spieghi che cosa misurano e come viene misurato, andando poi a specificare subito dopo il valore accettabile e quello preferibile

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/2_qualita_processo.tex
> +	\item \textbf{OPR07 Rischi non previsti}: : il verificarsi di imprevisti può accadere nel corso del progetto, ma devono poter essere rilevabili prima che succeda;
```suggestion
	\item \textbf{OPR07 Rischi non previsti}: il verificarsi di imprevisti può accadere nel corso del progetto, ma devono poter essere rilevabili prima che succeda;
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/7_valutazioni_miglioramento.tex
> +		corrisponde ad uno scatto dell'indice Z, l'aggiunta di nuove sezioni/paragrafi comporta lo scatto dell'indice Y.
```suggestion
		corrisponde ad uno scatto dell'indice Z, l'aggiunta di nuove sezioni/paragrafi comporta lo scatto dell'indice Y, l'aggiunta di nuove sezioni/paragrafi tali che essi rendano incompatibile il documento con le sue versioni precedenti corrisponde ad uno scatto dell'indice X.
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +mentre i colloqui e commenti si sono rivelati essenziali e esaustici al fine di comprendere le modifiche da apportare
```suggestion
mentre i colloqui e commenti si sono rivelati essenziali e esaustivi al fine di comprendere le modifiche da apportare
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +\paragraph{Risultati test fase di analisi}
```suggestion
\paragraph{Risultati controlli di qualità fase di analisi}
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
>  Qui di seguito verranno presentati i resoconti relativi ai test effettuati nella fase di analisi. \par
```suggestion
Qui di seguito verranno presentati i resoconti relativi ai controlli di qualità effettuati nella fase di analisi. \par
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OPR08 Rispetto obiettivi      			& MPR08 Obiettivi soddisfatti   & 100\%                                 & 100\%                & Superato       \\
Perché passano da OPR04 a OPR08?

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OPR12 Verifica documenti      			& MPR10 Frequenza controllo     & Ogni Milestone e modifica         	& Ogni Milestone       & Superato       \\
Gli indici sono disallineati

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +\paragraph{Risultati test fase di progettazione architetturale}
```suggestion
\paragraph{Risultati controlli di qualià fase di progettazione}
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +Qui di seguito verranno presentati i resoconti relativi ai test effettuati nella fase di progettazione architetturale. \par
```suggestion
Qui di seguito verranno presentati i resoconti relativi ai controlli di qualità effettuati nella fase di progettazione. \par
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OPR12 Verifica documenti      			& MPR10 Frequenza controllo     & Ogni Milestone e modifica         	& Ogni Milestone       & Superato       \\
Disallineati

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OP05 Assenza file senza intestazione	& MP05 File senza intestazione 	& 0										& 0						& Superato		\\
```suggestion
		OP01 Leggibilità testo       			& MP01 Indice di Gulpease      & 79,3                                  & \(\ge 60\)           & Superato       \\
		OP02 Correttezza ortografica 			& MP02 Errori ortografici      & 0                                     & 0                    & Superato       \\
		OP05 Assenza file senza intestazione	& MP05 File senza intestazione 	& 0										& 0						& Superato		\\
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OP02 Correttezza ortografica 			& MQP02 Errori ortografici      & 0                                     & 0                    & Superato       \\
```suggestion
		OP01 Leggibilità testo       			& MP01 Indice di Gulpease      & da completare                         & \(\ge 60\)           & Superato       \\
		OP02 Correttezza ortografica 			& MP02 Errori ortografici      & 0                                     & 0                    & Superato       \\
```

2021-03-05 16:37 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OPR08 Rispetto obiettivi      			& MPR08 Obiettivi soddisfatti   & 100\%                                 & 100\%                & Superato       \\
Salto negli indici come nella tabella precedente

2021-03-05 16:40 UTC, gpaparaz commented on esterni/piano_di_qualifica/src/2_qualita_processo.tex
> +	\item \textbf{OPR03 Budget totale}: mantenere le risorse messe a disposizione ad inizio progetto per tutta la sua durata;
il budget parziale è quello relativo alla singola fase, il totale è quello rendicontato che abbiamo messo nella prima lettera di presentazione per intenderci. L'altro giorno guardavo le slide di tullio e vedevo che quella cifra non deve essere assolutamente superata

2021-03-05 16:41 UTC, gpaparaz commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +Qui di seguito verranno presentati i resoconti relativi ai test effettuati nella fase di progettazione architetturale. \par
in teoria dovremmo avere due fasi di progettazione, la prima architetturale (cioè questa attuale), e la seconda che è la prossima, dove facciamo tutto il software. Non so però come Manuel ha chiamato le fasi, ho visto che aveva cambiato nomi

2021-03-05 16:42 UTC, danielcontro commented on esterni/piano_di_qualifica/src/2_qualita_processo.tex
> +	\item \textbf{OPR03 Budget totale}: mantenere le risorse messe a disposizione ad inizio progetto per tutta la sua durata;
Se sono cose diverse dovrebbero avere descrizioni diverse

2021-03-05 16:45 UTC, gpaparaz commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +		OPR08 Rispetto obiettivi      			& MPR08 Obiettivi soddisfatti   & 100\%                                 & 100\%                & Superato       \\
OPR05  - 06 è l'adempimento dei requisiti obbligatori e non, e non l'ho messo in RR perchè non avevamo fatto nulla di software. Non so se andrebbe messo ora. In teoria noi ci siamo dati degli obiettivi minimi quindi si, suppongo che sarà da mettere. 
Mi sono dimenticata i rischi

2021-03-05 16:47 UTC, danielcontro commented on esterni/piano_di_qualifica/src/5_resoconto_attivita.tex
> +Qui di seguito verranno presentati i resoconti relativi ai test effettuati nella fase di progettazione architetturale. \par
Ricordo che ci fosse la progettazione di qualcosa e la progettazione specifica(?) però secondo me conviene attenerci ai nomi delle revisioni (Revisione di Progettazione) e così andiamo sul sicuro

2021-03-05 16:48 UTC, gpaparaz commented on esterni/piano_di_qualifica/src/2_qualita_processo.tex
> +	\item \textbf{OPR03 Budget totale}: mantenere le risorse messe a disposizione ad inizio progetto per tutta la sua durata;
è vero ma non sapevo che descrizione mettergli perchè il concetto è lo stesso

2021-03-08 10:02 UTC, danielcontro reviewed
Le descrizioni delle metriche devono descrivere cosa viene misurato e non cosa rappresentano (es. MPR01 Varianza della pianificazione: viene calcolata la differenza tra il numero di giorni pianificati per il completamento di un prodotto e il numero di giorni effettivamente impiegati)

2021-03-09 18:47 UTC, danielcontro approved these changes

2021-03-09 18:48 UTC, merged