Merge capitolo 3 - Modello di sviluppo
Spaghetti-Code-G6/swe-docs pull request #92
Opened 2021-05-20 22:03 UTC by paguz42

2021-05-21 07:51 UTC, rizzostefano requested changes
Quali sono le funzionalità più importanti? Rendere esplicito che per funzionalità più importanti intendiamo quelle che sono dipendenze di altre funzionalità.
Ottimo il tracciamento incremento/requisito.

2021-05-21 11:26 UTC, gpaparaz commented
Questi incrementi sono relativi a tutto il progetto o ad una singola fase?

2021-05-21 15:59 UTC, paguz42 commented
> Questi incrementi sono relativi a tutto il progetto o ad una singola fase?

Si mi sa che è un refuso, questi sono gli incrementi totali, andrebbero lasciati quelli che non si riescono a fare per la prossima fase. A questo punto serve sapere cosa vogliamo finire entro la consegna

2021-05-21 16:45 UTC, paguz42 reviewed
Aggiornato paragrafo

2021-05-24 08:24 UTC, gpaparaz commented
Dal momento che in questa fase si è rifatto dall'inizio ciò che era stato fatto nella fase prima, è il caso di aggiungere gli incrementi della fase precedente?

2021-06-09 07:43 UTC, merged