Merge capitolo 6 - consuntivo
Spaghetti-Code-G6/swe-docs pull request #94
Opened 2021-05-20 22:05 UTC by paguz42

2021-05-21 08:05 UTC, rizzostefano requested changes
"A seguito dell'esito congelato della presentazione della Product Baseline, è stato necessario aumentare il numero di ore per ogni membro del gruppo." 
Aggiungerei un riferimento alla tabella sottostante, e soprattutto, nell'elenco appena sotto, cercherei di rendere più evidenti i ruoli che hanno consumato più ore.
Ok il preventivo a finire

2021-05-21 09:02 UTC, gpaparaz commented
Secondo me in questi consuntivi non serve aggiungere ore, anzi semmai toglierle, perchè noi abbiano fatto i preventivi in base ai vari requisiti che avremmo soddisfatto in questa fase. Se noi realizziamo meno requisiti di quelli che ci eravamo prefissati, lavoriamo di meno. Correggere gli errori che abbiamo fatto non va rendicontato

2021-05-28 11:21 UTC, rizzostefano requested changes
6_consuntivo.tex: riga 292 "Le ore assegnate ai ruoli ti" da riscrivere in "Le ore assegnate ai ruoli **di**"

per il resto mi sembra ok

2021-05-31 08:06 UTC, rizzostefano approved these changes

2021-05-31 08:06 UTC, merged